import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { MapPin, Trash2, Calendar, ArrowLeft, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const TripDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [trip, setTrip] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchTripDetails();
  }, [id]);

  const fetchTripDetails = async () => {
    try {
      const token = localStorage.getItem('token');
      const res = await axios.get(`/api/trips/${id}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setTrip(res.data);
      setLoading(false);
    } catch (error) {
      console.error("Error fetching trip", error);
      alert("Could not load trip");
      navigate('/trips');
    }
  };

  const downloadPDF = () => {
    const doc = new jsPDF();

    // 1. Title
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text(trip.title, 14, 22);

    // 2. Dates
    doc.setFontSize(11);
    doc.setTextColor(100);
    const dateStr = `${new Date(trip.startDate).toLocaleDateString()} - ${new Date(trip.endDate).toLocaleDateString()}`;
    doc.text(dateStr, 14, 32);

    // 3. Table of Places
    const tableColumn = ["#", "Place Name", "Address", "Status"];
    const tableRows = [];

    trip.places.forEach((place, index) => {
      const placeData = [
        index + 1,
        place.name,
        place.address,
        "Planned"
      ];
      tableRows.push(placeData);
    });


    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 40,
      theme: 'grid',
      styles: { fontSize: 10, cellPadding: 3 },
      headStyles: { fillColor: [66, 133, 244] }
    });

    // 4. Footer
    // Note: use 'lastAutoTable.finalY' to position below the table
    doc.setFontSize(10);
    doc.text("Generated by Tourist Place Checker App", 14, doc.lastAutoTable.finalY + 10);

    // 5. Save
    doc.save(`${trip.title}_Itinerary.pdf`);
  };

  const removePlace = async (placeId) => {
    if (!window.confirm("Remove this place from your itinerary?")) return;

    try {
      const token = localStorage.getItem('token');
      const res = await axios.delete(`/api/trips/${id}/place/${placeId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setTrip(res.data);
    } catch (error) {
      alert("Error removing place");
    }
  };

  if (loading) return <div className="text-center mt-10">Loading itinerary...</div>;
  if (!trip) return null;

  return (
    <div className="container mx-auto p-4 max-w-4xl">
      <button onClick={() => navigate('/trips')} className="flex items-center text-gray-500 hover:text-blue-600 mb-4">
        <ArrowLeft size={20} className="mr-1" /> Back to Trips
      </button>

      {/* Header Section */}
      <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white p-8 rounded-xl shadow-lg mb-8 flex justify-between items-center">
        <div>
          <h1 className="text-4xl font-bold mb-2">{trip.title}</h1>
          <div className="flex items-center gap-2 opacity-90">
            <Calendar size={18} />
            <span>
              {new Date(trip.startDate).toLocaleDateString()} — {new Date(trip.endDate).toLocaleDateString()}
            </span>
          </div>
        </div>

        <button
          onClick={downloadPDF}
          className="bg-white text-blue-700 px-4 py-2 rounded-lg font-bold shadow hover:bg-gray-100 flex items-center gap-2 transition"
        >
          <Download size={20} /> Download PDF
        </button>
      </div>

      {/* Places List */}
      <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
        <MapPin className="text-red-500" /> Itinerary ({trip.places.length} stops)
      </h2>

      {trip.places.length === 0 ? (
        <div className="text-center p-10 bg-gray-50 rounded-lg border border-dashed border-gray-300">
          <p className="text-gray-500">No places added yet.</p>
          <button onClick={() => navigate('/')} className="mt-2 text-blue-600 underline">
            Go search for places to add!
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          {trip.places.map((place, index) => (
            <div key={place.placeId} className="bg-white p-4 rounded-lg shadow border-l-4 border-blue-500 flex justify-between items-center">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="bg-blue-100 text-blue-800 text-xs font-bold px-2 py-1 rounded-full">
                    Stop #{index + 1}
                  </span>
                  <h3 className="text-lg font-bold">{place.name}</h3>
                </div>
                <p className="text-gray-600 text-sm">{place.address}</p>
              </div>

              <button
                onClick={() => removePlace(place.placeId)}
                className="text-red-400 hover:text-red-600 p-2 hover:bg-red-50 rounded-full transition"
                title="Remove from trip"
              >
                <Trash2 size={20} />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default TripDetails;